<?php

namespace App\Services;

use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Hash;
use YaangVu\LaravelBase\Services\impl\BaseService;

class UserService extends BaseService
{

    function createModel(): void
    {
        $this->model = new User();
    }

    public function add(object $request): Model
    {
        $rules = [
            'name' => 'required',
            'email' => 'required',
            'phone_number' => 'required'
        ];

        $this->doValidate($request, $rules);

        $request['password'] = Hash::make($request['password']);
        return parent::add($request); // TODO: Change the autogenerated stub
    }
}
